
# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

script:
- xcodebuild -workspace Example/MVOnboarding.xcworkspace -scheme MVOnboarding #builds framework 
- xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace Example/MVOnboarding.xcworkspace -scheme MVOnboarding-Example #builds example
